<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_update()
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function sapi_entity_interaction_entity_update(EntityInterface $entity){
  \Drupal::service('sapi_entity_interaction.entity_interaction_collector')->actionTypeTrigger($entity,'Update');
}

/**
 * Implements hook_entity_insert()
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function sapi_entity_interaction_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != 'sapi_data') {
    \Drupal::service('sapi_entity_interaction.entity_interaction_collector')->actionTypeTrigger($entity,'Create');
  }
}

/**
 * Implements hook_uninstall()
 *
 */
function sapi_entity_interaction_uninstall(){
  $configs = [
    'field.field.sapi_data.entity_interactions.field_entity_reference',
    'field.field.sapi_data.entity_interactions.field_interaction_type',
    'field.field.sapi_data.entity_interactions.field_user',
    'sapi.entity_interaction_config'
  ];
  foreach ($configs as $config) {
    Drupal::configFactory()->getEditable($config)->delete();
  }
}
