<?php

/**
 * @file
 * Contains sapi_entity_interaction.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_update().
 */
function sapi_entity_interaction_entity_update(EntityInterface $entity) {
  \Drupal::service('sapi_entity_interaction.entity_interaction_collector')->actionTypeTrigger($entity, 'Update');
}

/**
 * Implements hook_entity_insert().
 */
function sapi_entity_interaction_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != 'sapi_data') {
    \Drupal::service('sapi_entity_interaction.entity_interaction_collector')->actionTypeTrigger($entity, 'Create');
  }
}
