sapi_data.sapi_data_type.*:
  type: config_entity
  label: 'Statistics API Data entry type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
