sapi.statistics_plugins:
  type: config_object
  label: 'Statistics plugin settings'
  mapping:
    enabled:
      type: sequence
      label: 'Enabled statistics plugins'
      sequence:
        type: string
        label: 'Statistics plugin name'
